### ISSUE TITLE
Error: Cannot find module './error'

### ISSUE THREAD

**Issue by rep14** [bettimms/multi-gekko#8]
module.js:550
    throw err;
    ^

Error: Cannot find module './error'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/joe/gekko/core/util.js:8:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by bettimms** [comment]
Something wrong on your side. Please make sure you've followed the steps. I'm not using gekko since almost a year now I dont know if they've changed anything, but similar cases is reported here many times and it's usually a problem in your side.
